require("CHPastel/plugins/bufferline")
require("CHPastel/plugins/nvim-cmp")
require("CHPastel/plugins/nvim-lsp")
require("CHPastel/plugins/nvim-tree")
require("CHPastel/plugins/nvim-treesitter")
require("CHPastel/plugins/nvim-ts-rainbow")
require("CHPastel/plugins/packer")
require("CHPastel/plugins/telescope")
