local colors = require("CHPastel.utils").colors
local styles = require("CHPastel.utils").styles
local Group = require("CHPastel.utils").Group

Group.new("TSError", colors.red:light(), nil, nil)
Group.new("TSPunctDelimiter", colors.white, nil, nil)
Group.new("TSPunctBracket", colors.white, nil, nil)
Group.new("TSPunctSpecial", colors.purple, nil, nil)
-- Constant
Group.new("TSConstant", colors.white, nil, nil)
Group.new("TSConstBuiltin", colors.purple, nil, styles.italic)
Group.new("TSConstMacro", colors.cyan, nil, nil)
Group.new("TSStringRegex", colors.green, nil, nil)
Group.new("TSString", colors.light_green, nil, nil)
Group.new("TSStringEscape", colors.light_green, nil, nil)
Group.new("TSStringSpecial", colors.green, nil, styles.italic)
Group.new("TSCharacter", colors.purple, nil, nil)
Group.new("TSNumber", colors.purple, nil, nil)
Group.new("TSBoolean", colors.purple, nil, styles.italic)
Group.new("TSFloat", colors.purple, nil, nil)
Group.new("TSAnnotation", colors.yellow, nil, nil)
Group.new("TSAttribute", colors.yellow, nil, nil)
Group.new("TSNamespace", colors.white, nil, styles.italic)
-- Functions
Group.new("TSFuncBuiltin", colors.yellow, nil, nil)
Group.new("TSFunction", colors.yellow, nil, nil)
Group.new("TSFuncMacro", colors.yellow, nil, nil)
Group.new("TSParameter", colors.yellow, nil, nil)
Group.new("TSParameterReference", colors.yellow, nil, nil)
Group.new("TSMethod", colors.yellow, nil, nil)
Group.new("TSField", colors.white, nil, nil)
Group.new("TSProperty", colors.cyan, nil, styles.italic)
Group.new("TSConstructor", colors.light_green, nil, nil)
-- Keywords
Group.new("TSConditional", colors.yellow, nil, nil)
Group.new("TSRepeat", colors.yellow, nil, nil)
Group.new("TSLabel", colors.yellow, nil, nil)
Group.new("TSKeyword", colors.yellow, nil, styles.italic)
Group.new("TSKeywordFunction", colors.purple, nil, styles.bold + styles.italic)
Group.new("TSKeywordOperator", colors.yellow, nil, nil)
Group.new("TSOperator", colors.yellow, nil, nil)
Group.new("TSException", colors.purple, nil, nil)
Group.new("TSType", colors.yellow, nil, nil)
Group.new("TSTypeBuiltin", colors.yellow, nil, nil)
Group.new("TSStructure", colors.cyan, nil, nil)
Group.new("TSInclude", colors.yellow, nil, styles.italic)
-- Variable
Group.new("TSVariable", colors.white, nil, nil)
Group.new("TSVariableBuiltin", colors.yellow, nil, nil)
-- Text
Group.new("TSText", colors.white, nil, nil)
Group.new("TSStrong", colors.white, nil, styles.bold)
Group.new("TSEmphasis", colors.white, nil, styles.italic)
Group.new("TSUnderline", colors.white, nil, styles.underline)
Group.new("TSTitle", colors.yellow, nil, styles.bold)
Group.new("TSLiteral", colors.light_green, nil, nil)
Group.new("TSURI", colors.cyan, nil, styles.underline)
-- Tags
Group.new("TSTag", colors.yellow, nil, nil)
Group.new("TSTagDelimiter", colors.cyan, nil, nil)
