local Color = require("CHPastel.utils").Color
local palette = require("CHPastel.palette")

-- colors
Color.new("black", palette.black)
Color.new("darkest_grey", palette.darkest_grey)
Color.new("darker_grey", palette.darker_grey)
Color.new("dark_grey", palette.dark_grey)
Color.new("grey", palette.grey)
Color.new("light_grey", palette.light_grey)
Color.new("lighter_grey", palette.lighter_grey)
Color.new("lightest_grey", palette.lightest_grey)
Color.new("white", palette.white)
Color.new("yellow", palette.yellow)
Color.new("yellow", palette.yellow)
Color.new("yellow", palette.yellow)
Color.new("yellow", palette.yellow)
Color.new("darkest_green", palette.darkest_green)
Color.new("dirty_green", palette.dirty_green)
Color.new("green", palette.green)
Color.new("light_green", palette.light_green)
Color.new("lighter_green", palette.lighter_green)
Color.new("lightest_green", palette.lightest_green)
Color.new("purple", palette.purple)
Color.new("purple", palette.purple)
Color.new("purple", palette.purple)
Color.new("chpastel_bg", palette.chpastel_bg)
Color.new("darkest_blue", palette.darkest_blue)
Color.new("darker_blue", palette.darker_blue)
Color.new("dark_blue", palette.dark_blue)
Color.new("blue", palette.blue)
Color.new("light_blue", palette.light_blue)
Color.new("greyish_blue", palette.greyish_blue)
Color.new("dirty_blue", palette.dirty_blue)
Color.new("red", palette.red)
Color.new("red", palette.red)
Color.new("red", palette.red)
Color.new("red", palette.red)
Color.new("purple", palette.purple)
Color.new("purple", palette.purple)
Color.new("purple", palette.purple)
Color.new("purple", palette.purple)
Color.new("purple", palette.purple)
Color.new("purple", palette.purple)
Color.new("cursor_line", palette.cursor_line)
Color.new("cursor_hover", palette.cursor_hover)

-- applying highlights
require("CHPastel.theme")
require("CHPastel.syntax")
require("CHPastel.plugins")
require("CHPastel.languages")
